project:
  type: website
  output-dir: docs

website:
  title: "Inquiring Minds Want to Know"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com//rbarbanell
   
format:
  html:
    theme: vapor
    css: styles.css



