project:
  type: website
  output-dir: docs

website:
  comments: 
    utterances: 
      repo: quarto-dev/quarto-web
      theme: gruvbox-dark
  title: "Inquiring Minds Want to Know"
  navbar:
    background: dark
    search: true
    right:
      - about.qmd
      - icon: ballon-heart
        file: dangsdesign.qmd
      - icon: github
        href: https://github.com//rbarbanell
      - posts.qmd
    
     
      
      
 
        
    
      
   
format:
  html:
    theme: sandstone
    mainfont: courier new 
    css: styles.css
    code-fold: true
    code-summary: "Here is the code"




