project:
  type: website
  output-dir: docs

website:
  reader-mode: true
  title: "Inquiring Minds Want to Know"
  navbar:
    background: dark
    search: true
    right:
      - about.qmd
      - icon: github
        href: https://github.com//rbarbanell
 
        
    
      
   
format:
  html:
    theme: vapor
    css: styles.css



