---
title: "Who am I"
author: "Rebecca Barbanell"
format:
  revealjs: 
    theme: beige
    incremental: true 
    transition: slide
    background-transition: fade
    
---
## Biography {.smaller}

Rebecca Barbanell is a data scientist who approaches her work holistically and values a humanistic perspective in technology. She is currently pursuing a M.S in Data Science at Willamette University and holds a B.S in Data Science from the same institution. Previously, she worked as a Data Engineer Intern for the Ness of Brodgar archaeological dig in Scotland, where she generated and managed geo-chemical data for soil samples. Before that, she worked as a mathematics tutor at Seattle Central College, where she specialized in simplifying math concepts and coaching students to think critically. Rebecca is also a dedicated leader and volunteer, having served as President of the Women in Science and Engineering Club and Treasurer of the Society for Advancement of Chicanos/Hispanics and Native Americans in Science. In her free time, Rebecca enjoys exploring nature with her dog, making food, playing music, and having fun.


## Slide 2

## Slide 3 {visibility="uncounted"}